### PR TITLE
Fix #82, Convert integers holding boolean truth values to `bool`

### LINKED ISSUE #82: Integers representing boolean truth values should be converted to `bool`
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
There are a few variables in CS represented by integers when they only ever hold boolean `true`/`false` values.

**Code snips**
https://github.com/nasa/CS/blob/bd4dd1ce688e9af683e63132b37306b21f320ab2/fsw/inc/cs_tbldefs.h#L84
https://github.com/nasa/CS/blob/bd4dd1ce688e9af683e63132b37306b21f320ab2/fsw/inc/cs_msg.h#L51-L52

**Expected behavior**
Integers representing boolean truth values should be converted `bool` - this makes the intent clearer and improves maintainability.

**Reporter Info**
Avi Weiss @thnkslprpt

### PR DESCRIPTION
**Pull request by thnkslprpt**
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
- Fixes #82
  - 1 integer variable which only ever holds boolean truth values has been converted to `bool`

**Testing performed**
GitHub CI actions all passing successfully.

**Expected behavior changes**
No change to behavior.
- intent of these variables is more clear
- improved type-safety
- eases future maintainability

**Contributor Info**
Avi Weiss @thnkslprpt

### CODE REVIEW

File: fsw/inc/cs_msg.h [hunk 1]
```diff
@@ -48,8 +48,8 @@ typedef struct
     uint8   TablesCSState;               /**< \brief CS Tables table checksum state */
     uint8   OSCSState;                   /**< \brief OS code segment checksum state */
     uint8   CfeCoreCSState;              /**< \brief cFE Core code segment checksum stat e*/
-    uint8   RecomputeInProgress;         /**< \brief CS "Recompute In Progress" flag */
-    uint8   OneShotInProgress;           /**< \brief CS "OneShot In Progress" flag */
+    bool    RecomputeInProgress;         /**< \brief CS "Recompute In Progress" flag */
+    bool    OneShotInProgress;           /**< \brief CS "OneShot In Progress" flag */
```
Comment (jphickey) [inline fsw/inc/cs_msg.h:52]: Things in "msg.h" affect inter-processor interfaces, so these should be limited should stay explicit about the width (i.e. keep using `uint8` here)

File: fsw/inc/cs_tbldefs.h [hunk 2]
```diff
@@ -81,7 +81,8 @@ typedef struct
 {
     cpuaddr StartAddress;       /**< \brief The Start address to Checksum */
     uint16  State;              /**< \brief Uses the CS_STATE_... defines from above */
-    uint16  ComputedYet;        /**< \brief Have we computed an Integrity value yet */
+    bool    ComputedYet;        /**< \brief Have we computed an Integrity value yet */
+    bool    Filler8;            /** <\brief Padding */
```
Comment (jphickey) [inline fsw/inc/cs_tbldefs.h:85]: Same comment here, this should stay as `uint16` to be explicit.  This file is an interface.

**Review by jphickey — CHANGES_REQUESTED** [review]
We need to be sure that we don't change the tables or command message formats with this

**Review by jphickey — CHANGES_REQUESTED** [review]
I think we still need to revert the changes to "cs_tbldefs.h" ....  Everything in this struct should be based on known-width types only - no "bool" or "cpuaddr".  So there were prexisting problems there.  But the proposed change will alter alignment and still uses bool and cpuaddr.  

The change to "cs_compute.c" is good though.

**Comment by thnkslprpt** [comment]
> I think we still need to revert the changes to "cs_tbldefs.h" .... Everything in this struct should be based on known-width types only - no "bool" or "cpuaddr". So there were prexisting problems there. But the proposed change will alter alignment and still uses bool and cpuaddr.
> 
> The change to "cs_compute.c" is good though.

@jphickey No worries - I removed the changes to `cs_tbldefs.h` - unless you want me to remove the `bool`'s that are already in there?

**Review by jphickey — APPROVED** [review]
